
language: ruby
rvm:
  - 2.6.0
cache: 
  directories:
    - /home/travis/.rvm/
before_script:
  - gem update --system
  - gem install bundler
  - gem install awesome_bot
script:
  - awesome_bot README.md --allow-redirect --white-list mastodon
