language: ruby
rvm:
  - 2.6.3
cache:
  directories:
    - /home/travis/.rvm/
before_script:
  - gem up --system --no-document
  - gem i bundler awesome_bot --no-document
script:
  - awesome_bot README.md --allow-redirect --white-list mastodon
